version: '3.9'
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql